### ISSUE TITLE
Consider using yarn

### ISSUE THREAD

**Issue by oshalygin** [camsjams/node-treasury#3]
For faster CI builds and consistency that yarn.lock provides

**Comment by oshalygin** [comment]
Any update?  I actually would like to use node-treasury in a project, @camsjams :)

**Comment by camsjams** [comment]
Still tracking this, we should have something for you soon.

**Comment by camsjams** [comment]
See PR https://github.com/camsjams/node-treasury/pull/7 and [build status](https://circleci.com/gh/camsjams/node-treasury/52) from Circle

**Comment by oshalygin** [comment]
Oh man thanks @camsjams

**Comment by camsjams** [comment]
Published: https://www.npmjs.com/package/treasury
