### ISSUE TITLE
Even while redis/memcached is running, those modules need to be brought in for dev

### ISSUE THREAD

**Issue by oshalygin** [camsjams/node-treasury#4]
Consider not having memcached and redis be global node installations for users.  

![image](https://cloud.githubusercontent.com/assets/7675942/20035015/df26d26a-a390-11e6-948a-a2c0a07ac0c7.png)

![image](https://cloud.githubusercontent.com/assets/7675942/20035016/e471bc44-a390-11e6-9178-8d5148a19030.png)

after installing the dev dependencies, 
![image](https://cloud.githubusercontent.com/assets/7675942/20035017/f17e74ea-a390-11e6-8f80-a4c93c3602bf.png)

**Comment by camsjams** [comment]
The intended design for this module was to not install both the redis-client and the memcached client as dependencies, and this doesn't require the implementer to use global installation, but rather local installations - same goes for the Bluebird or Q modules. The cache client is [inferred](https://github.com/camsjams/node-treasury/blob/master/lib/adapters.js#L7-L36).

Good catch on the dev dependencies. I installed them in the CI environment at least: https://github.com/camsjams/node-treasury/blob/master/circle.yml#L12-L15

But other people that contribute might want these tests to work locally as well 👍
